03 mongodb
chertoha/nodejs-homework-rest-api pull request #3
Opened 2023-01-30 19:34 UTC by chertoha

2023-01-31 18:08 UTC, Eastvarga requested changes
Є зауваження

2023-01-31 18:08 UTC, Eastvarga commented on controllers/contactsController.js
> +    throw new WrongParamsError("Missing field favorite");
Це логіка валідації зробіть схему валідації для цього раута та мідлвар валідації, котрий буде працювати до контроллера

2023-01-31 18:08 UTC, Eastvarga commented on routes/api/contacts.js
> +router.patch("/:contactId/favorite", asyncWrapper(setFavorite));
Сюди додайте валідацію тіла запиту

2023-02-01 07:25 UTC, chertoha commented on routes/api/contacts.js
> +router.patch("/:contactId/favorite", asyncWrapper(setFavorite));
Виправив. У validationMiddleware.js додав валідацію favoriteValidation. прокинув її мідлваром у роутері, та прибрав зайве в контроллері

2023-02-01 18:05 UTC, Eastvarga approved these changes

2023-02-01 18:05 UTC, merged